development: &default
  adapter: postgresql
  encoding: unicode
  database: hound_development
  pool: 5
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>

test:
  <<: *default
  database: hound_test

production:
  <<: *default
  database: hound_production
